"""schema v2: structured reports, agent traces, SEC filing RAG

Revision ID: a1f2c3d4e5f6
Revises: db3acf5592f3
Create Date: 2026-07-11

Hand-written (not autogenerated): pgvector columns and the HNSW index need
explicit DDL, and the research_reports restructure replaces free-text report
columns with structured JSONB (dev data is disposable; no data migration).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects.postgresql import JSONB

revision: str = "a1f2c3d4e5f6"
down_revision: str | Sequence[str] | None = "db3acf5592f3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

EMBEDDING_DIM = 1536


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # --- research_reports: free-text columns -> structured JSONB ---
    for col in (
        "report_v1",
        "report_v2",
        "was_revised",
        "fundamentals_output",
        "risk_output",
        "sentiment_output",
        "critic_challenges_found",
        "critic_assessment",
    ):
        op.drop_column("research_reports", col)

    op.add_column("research_reports", sa.Column("verdict", sa.String(20), nullable=True))
    op.add_column("research_reports", sa.Column("overall_score", sa.Float(), nullable=True))
    op.add_column("research_reports", sa.Column("report", JSONB(), nullable=True))
    op.add_column(
        "research_reports",
        sa.Column("revision_count", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column("research_reports", sa.Column("critic", JSONB(), nullable=True))
    op.add_column("research_reports", sa.Column("error", sa.Text(), nullable=True))
    op.add_column("research_reports", sa.Column("latency_ms", sa.Integer(), nullable=True))
    op.create_index("ix_research_reports_ticker", "research_reports", ["ticker"])
    op.create_index("ix_research_reports_created_at", "research_reports", ["created_at"])

    # --- agent_runs: per-agent traces (ADR-8) ---
    op.create_table(
        "agent_runs",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column(
            "report_id",
            sa.Uuid(),
            sa.ForeignKey("research_reports.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("agent_name", sa.String(50), nullable=False),
        sa.Column("phase", sa.String(30), nullable=False),
        sa.Column("status", sa.String(20), nullable=False, server_default="complete"),
        sa.Column("model", sa.String(50), nullable=False),
        sa.Column("output", JSONB(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("output_tokens", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("cost_usd", sa.Float(), nullable=False, server_default="0"),
        sa.Column("latency_ms", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
    )
    op.create_index("ix_agent_runs_report_id", "agent_runs", ["report_id"])

    # --- filings + filing_chunks: SEC EDGAR RAG store (ADR-5) ---
    op.create_table(
        "filings",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("ticker", sa.String(10), nullable=False),
        sa.Column("cik", sa.String(10), nullable=False),
        sa.Column("form_type", sa.String(10), nullable=False),
        sa.Column("accession_no", sa.String(25), nullable=False, unique=True),
        sa.Column("filing_date", sa.String(10), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("chunk_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("ingested_at", sa.DateTime(), nullable=False),
    )
    op.create_index("ix_filings_ticker", "filings", ["ticker"])

    op.create_table(
        "filing_chunks",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column(
            "filing_id", sa.Uuid(), sa.ForeignKey("filings.id", ondelete="CASCADE"), nullable=False
        ),
        sa.Column("item", sa.String(10), nullable=False),
        sa.Column("section_title", sa.String(120), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("embedding", Vector(EMBEDDING_DIM), nullable=True),
    )
    op.create_index("ix_filing_chunks_filing_id", "filing_chunks", ["filing_id"])
    op.execute(
        "CREATE INDEX ix_filing_chunks_embedding_hnsw ON filing_chunks "
        "USING hnsw (embedding vector_cosine_ops)"
    )


def downgrade() -> None:
    op.drop_table("filing_chunks")
    op.drop_table("filings")
    op.drop_table("agent_runs")

    op.drop_index("ix_research_reports_created_at", table_name="research_reports")
    op.drop_index("ix_research_reports_ticker", table_name="research_reports")
    for col in ("latency_ms", "error", "critic", "revision_count", "report", "overall_score", "verdict"):
        op.drop_column("research_reports", col)

    op.add_column("research_reports", sa.Column("report_v1", sa.Text(), nullable=True))
    op.add_column("research_reports", sa.Column("report_v2", sa.Text(), nullable=True))
    op.add_column(
        "research_reports",
        sa.Column("was_revised", sa.Boolean(), nullable=False, server_default="false"),
    )
    op.add_column("research_reports", sa.Column("fundamentals_output", sa.Text(), nullable=True))
    op.add_column("research_reports", sa.Column("risk_output", sa.Text(), nullable=True))
    op.add_column("research_reports", sa.Column("sentiment_output", sa.Text(), nullable=True))
    op.add_column("research_reports", sa.Column("critic_challenges_found", sa.Integer(), nullable=True))
    op.add_column("research_reports", sa.Column("critic_assessment", sa.Text(), nullable=True))
